### PR TITLE
x86_64: Enable creation of .dynamic section

### LINKED ISSUE #534: Implement x86_64 target backend in ELD
Summary
- Implement an x86_64 target backend for the ELD linker.
- Phase 1 targets static linking support (Linux + baremetal), with the goal of passing unit tests and producing working binaries.
- Future phases can extend to dynamic linking, symbol versioning, and broader GNU compatibility.

Goals
- Add a new x86_64 target backend that:
  - Builds in the ELD tree and integrates with ELD’s plugin/target architecture
  - Handles core ELF x86_64 relocations for static linking, including common PC-relative and absolute relocations
  - Supports basic TLS relocations needed for static/PIC cases
  - Produces detailed map files
  - Works with ELD’s linker script parser (GNU-compatible where applicable)
  - Normalizes target triples (e.g., x86_64-linux-gnu vs x86_64-unknown-linux-gnu)
  - Passes CI on Linux; optional Windows build check if feasible

Non-Goals (Phase 1)
- Full dynamic linking (GLIBC symbol versioning, PLT/GOT for shared libraries)
- Advanced GNU script edge cases beyond commonly used constructs
- Comprehensive Windows support (can be planned separately)

Scope & Deliverables
- New x86_64 target backend module(s) in ELD
- Core relocation handling (examples: 64-bit absolute, 32/32S, common PC-relative forms, minimal TLS)
- Section merging (.text, .data, .bss), alignment, start address handling aligned with triple/OS
- Linker script compatibility for common patterns; ensure parser handles “: ALIGN(…)” spacing expectations
- Detailed map-file output with target triple environment
- Reproduce tar functionality remains working when linking x86_64
- Docs: brief “Getting started” + “Supported features/limitations” + “Examples”
- Tests: LIT/unit tests for relocations, script handling, map output

User Scenarios
- Static link a simple C/C++ program targeting x86_64 (baremetal and Linux/musl)
- Link with a simple GNU-style linker script (SECTIONS, ALIGN, basic placement)
- Produce a readable map file confirming sections, symbols, and target triple environment

Work Breakdown (Checklist)
1) Environment & Planning
   - [x] Build ELD locally (Linux) and read target backend guidelines
   - [x] Confirm initial scope (static linking, minimal TLS, map files, scripts)
   - [ ] Pick initial triples to support (e.g., x86_64-unknown-linux-gnu, x86_64-none-elf)

2) Target Backend Skeleton
   - [x] Create x86_64 target descriptor (endianness, pointer size, data layout)
   - [ ] Register backend and wiring in CMake/build

3) Object & Sections
   - [x] Parse ELF x86_64 objects and collect sections/symbols
   - [ ] Implement section merging (.text/.data/.bss), alignment rules
   - [x] Ensure init_array/fini_array support in line with ELD direction

4) Relocations (Phase 1 set)
   - [x] Implement core absolute and PC-relative relocations commonly needed for static linking
   - [x] Minimal TLS models sufficient for static/PIC cases (document exactly what’s supported)
   - [ ] Add relocation-specific diagnostics

5) Linker Script Compatibility
   - [x] Validate common GNU constructs (SECTIONS, ALIGN, KEEP, GROUP, etc.)
   - [ ] Ensure parser behavior with “: ALIGN(…)” vs “:ALIGN(…)”; document user guidance

6) Triple Handling & Defaults
   - [ ] Normalize x86_64 triples and map OS environment for map-file output
   - [ ] Ensure consistent behavior when LLVM default triple differs (unknown vs linux)

7) Map Files & Reproduce
   - [ ] Add x86_64 metadata to detailed map file (environment/triple, layout)
   - [ ] Verify reproduce tar generation works on failures

8) CI & Tooling
   - [ ] Add GitHub Actions workflow (Linux) building ELD + running tests
   - [ ] Optional: Windows workflow stub (tracked separately if needed)

9) Tests
   - [ ] LIT tests: relocations (absolute, PC-relative), TLS (if in scope), script parsing (ALIGN), map-file content
   - [ ] Sample baremetal and Linux static link tests
   - [ ] Negative tests for invalid script/input section descriptions (ensure proper errors)

10) Documentation
   - [ ] Add “x86_64 backend – quick start” doc: how to build, invoke, and known limitations
   - [ ] Update linker script GNU-compat docs and examples (include ALIGN spacing note)
   - [ ] Add a simple end-to-end example

Risks & Dependencies
- Triple normalization can change layout assumptions (e.g., marking OS as linux vs none); tests must set explicit triples
- Windows builds may require minor source changes and CI adjustments
- Future dynamic linking/symbol versioning is out-of-scope; plan a follow-up issue

Testing Plan
- Unit/LIT tests for:
  - Core relocations resolve correctly and produce expected bytes
  - Script parsing: SECTIONS with ALIGN; verify no crashes and correct diagnostics
  - Map-file: includes “Target triple environment” and sane layout details
- End-to-end: build+link sample x86_64 static binaries (baremetal and Linux/musl)
- Reproduce tar: ensure it captures inputs for debugging

Definition of Done (Phase 1)
- ✅ ELD builds with the x86_64 backend enabled on Linux
- ✅ Core relocations pass unit/LIT tests
- ✅ A simple static binary links and runs (baremetal or Linux/musl), with correct sections/layout
- ✅ Map-file shows triple environment and section/symbol details
- ✅ CI green on Linux (libc test suite using musl); docs published; known limitations listed

### PR DESCRIPTION
**Pull request by bhoumik03**
Add x86_64ELFDynamic and wire it into the backend; instantiate in doPreLayout for dynamic outputs.
Adjust StandaloneInfo to not force static for dynamic/PIE, enabling .interp and .dynamic.
Add a lit test to verify presence of PT_INTERP/PT_DYNAMIC and .interp/.dynamic for a minimal PIE linked with --force-dynamic.

Fixes #534

### CODE REVIEW

File: lib/Target/x86_64/x86_64ELFDynamic.cpp [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+#include "eld/Target/GNULDBackend.h"
+#include "eld/Config/LinkerConfig.h"
+#include "eld/Target/ELFFileFormat.h"
+
+using namespace eld;
+
+x86_64ELFDynamic::x86_64ELFDynamic(GNULDBackend &pParent, LinkerConfig &pConfig)
+    : ELFDynamic(pParent, pConfig) {}
+
+x86_64ELFDynamic::~x86_64ELFDynamic() {}
```
Comment (parth-07) [inline lib/Target/x86_64/x86_64ELFDynamic.cpp]: Please remove the destruction definition. A trivial destruction definition is redundant, and can inhibit optimizations.

File: lib/Target/x86_64/x86_64LDBackend.cpp [hunk 2]
```diff
@@ -119,6 +120,16 @@ bool x86_64LDBackend::finalizeTargetSymbols() {
   return true;
 }
 
+void x86_64LDBackend::doPreLayout() {
+  // Create a dynamic section handler for non-static or forced-dynamic outputs.
+  if ((!config().isCodeStatic() || config().options().forceDynamic())) {
```
Comment (parth-07) [inline lib/Target/x86_64/x86_64LDBackend.cpp]:
```suggestion
  if (!config().isCodeStatic() || config().options().forceDynamic()) {
```

File: lib/Target/x86_64/x86_64LDBackend.cpp [hunk 3]
```diff
@@ -119,6 +120,16 @@ bool x86_64LDBackend::finalizeTargetSymbols() {
...
+    if (nullptr == m_pDynamic)
```
Comment (parth-07) [inline lib/Target/x86_64/x86_64LDBackend.cpp]: is `doPreLayout` called multiple times?

File: lib/Target/x86_64/x86_64ELFDynamic.cpp (hunk 1 above)
Comment (bhoumik03) [reply lib/Target/x86_64/x86_64ELFDynamic.cpp]: okay

File: lib/Target/x86_64/x86_64LDBackend.cpp (hunk 3 above)
Comment (bhoumik03) [reply lib/Target/x86_64/x86_64LDBackend.cpp]: No, it is not called multiple times. Removed the nullptr check.

File: test/x86_64/linux/InterpAndDynamicBasicTest/InterpAndDynamicBasic.test [hunk 4]
```diff
@@ -0,0 +1,20 @@
...
+# - Checks PT_INTERP and PT_DYNAMIC exist
+# - Checks .interp and .dynamic sections present
+#END_COMMENT
+
+#START_TEST
+RUN: %clang %clangopts -fPIE -pie -c %p/Inputs/1.c -o %t.1.o
+RUN: %link %linkopts --force-dynamic -o %t.out %t.1.o
+
+# Basic presence of dynamic structures
+RUN: readelf -l %t.out | %filecheck %s --check-prefix=PHDRS
```
Comment (parth-07) [inline test/x86_64/linux/InterpAndDynamicBasicTest/InterpAndDynamicBasic.test]:
```suggestion
RUN: %readelf -l %t.out | %filecheck %s --check-prefix=PHDRS
```

File: test/x86_64/linux/InterpAndDynamicBasicTest/InterpAndDynamicBasic.test [hunk 5]
```diff
@@ -0,0 +1,20 @@
...
+PHDRS: INTERP
+PHDRS: DYNAMIC
+RUN: readelf -S %t.out | %filecheck %s --check-prefix=SECTS
```
Comment (parth-07) [inline test/x86_64/linux/InterpAndDynamicBasicTest/InterpAndDynamicBasic.test]:
```suggestion
RUN: %readelf -S %t.out | %filecheck %s --check-prefix=SECTS
```

File: lib/Target/x86_64/x86_64LDBackend.h [hunk 6]
```diff
@@ -12,7 +12,9 @@
 #include "eld/Readers/ELFSection.h"
 #include "eld/SymbolResolver/IRBuilder.h"
 #include "eld/Target/GNULDBackend.h"
+#include "x86_64ELFDynamic.h"
 #include "x86_64PLT.h"
+#include "llvm/BinaryFormat/ELF.h"
```
Comment (parth-07) [inline lib/Target/x86_64/x86_64LDBackend.h]: Do we need this header here?

File: test/x86_64/linux/InterpAndDynamicBasicTest/InterpAndDynamicBasic.test [hunk 7]
```diff
@@ -0,0 +1,20 @@
+#--InterpAndDynamicBasic.test----------Executable (PIE)--------#
+
+BEGIN_COMMENT
```
Comment (parth-07) [inline test/x86_64/linux/InterpAndDynamicBasicTest/InterpAndDynamicBasic.test]:
```suggestion
#BEGIN_COMMENT
```

File: test/x86_64/linux/InterpAndDynamicBasicTest/InterpAndDynamicBasic.test [hunk 8]
```diff
@@ -0,0 +1,20 @@
...
+# Verify dynamic foundation emits interpreter and dynamic section.
+# - Builds a minimal PIE
+# - Checks PT_INTERP and PT_DYNAMIC exist
+# - Checks .interp and .dynamic sections present
+#END_COMMENT
+
```
Comment (parth-07) [inline test/x86_64/linux/InterpAndDynamicBasicTest/InterpAndDynamicBasic.test]: Please remove the redundant newlines.

File: lib/Target/x86_64/x86_64LDBackend.h (hunk 6 above)
Comment (bhoumik03) [reply lib/Target/x86_64/x86_64LDBackend.h]: It's not required, removed it.

**Review by partaror — APPROVED** [review]

**Review by quic-seaswara — APPROVED** [review]
