### PR TITLE
Fix fragment padding size computation when output section is unaligned

### LINKED ISSUE #346: map file shows improper section addresses
Below test shows incorrect addresses in the map file :-

```
cat > script.t << '!'
SECTIONS {
  text (0x14) : {
    *(.text*)
  }
}
!

cat > test.c << '!'
int foo() { return 1; }
int bar() { return 0; }
!

clang -falign-functions=64 --target=riscv32-unknown-elf -c test.c -ffunction-sections
ld.eld test.o -T script.t -Map map.txt -o eld.out
```

**Map file snippet**

```
text    0x14    0x7e # Offset: 0x1014, LMA: 0x40, Alignment: 0x40, Flags: SHF_ALLOC|SHF_EXECINSTR, Type: SHT_PROGBITS
# RelaxationBytesDeleted : 36
*(.text*) #Rule 1, script.t [3:0]
.text   0x14    0x0     test.o  #SHT_PROGBITS,SHF_ALLOC|SHF_EXECINSTR,2
.text.foo       0x14    0x3e    test.o  #SHT_PROGBITS,SHF_ALLOC|SHF_EXECINSTR,64
        0x40            $x
        0x40            foo
PADDING_ALIGNMENT       0x52    0x2     0x0
.text.bar       0x54    0x3e    test.o  #SHT_PROGBITS,SHF_ALLOC|SHF_EXECINSTR,64
        0x80            $x
        0x80            bar
*(text) #Rule 2, Internal-LinkerScript (Implicit rule inserted by Linker) [0:0]
```

### PR DESCRIPTION
**Pull request by parth-07**
This commit fixes fragment padding size computation when output section address is unaligned. The fragment padding size computation (incorrectly) assumed that the fragment offset is congruent to the output section address (modulo fragment alignment). This assumption is violated when the output section address is explicitly specified in the linker script.

This change is causing UnalignedCrash.test to fail because the test expects the link to fail but now the link is passing. The link passing seems correct as both bfd/lld pass as well for this test case.

Resolves #346

### CODE REVIEW

File: lib/Fragment/Fragment.cpp [hunk 1]
```diff
@@ -107,7 +108,14 @@ Fragment *Fragment::getNextNode() {
...
   if (!hasOffset())
     return 0;
-  return llvm::offsetToAlignment(UnalignedOffset, llvm::Align(Alignment));
+  // FIXME: Will a fragment ever not have an owning section / output section?
+  // We should have linker invariants such as 'All fragments must always have a
+  // fragment' so that we can write codes in a uniform way without having too
+  // many if-checks.
+  ELFSection *OutSect = (OwningSection ? getOutputELFSection() : nullptr);
+  size_t OutSectAddr = (OutSect ? OutSect->addr() : 0);
+  return llvm::offsetToAlignment(UnalignedOffset + OutSectAddr,
```
Comment (quic-seaswara) [inline lib/Fragment/Fragment.cpp:117]: This should probably use dotSymbol->value() ?

File: test/UnitTests/CMakeLists.txt [hunk 2]
```diff
@@ -7,6 +7,7 @@ set(LLVM_LINK_COMPONENTS
     LTO
     MC
     Object
+    Option
```
Comment (quic-seaswara) [inline test/UnitTests/CMakeLists.txt:10]: Why this change ?

**Review by quic-seaswara — CHANGES_REQUESTED** [review]

File: test/UnitTests/CMakeLists.txt (hunk 2 above)
Comment (parth-07) [reply test/UnitTests/CMakeLists.txt:10]: I accidentally pushed this change. Thank you for catching this. I am removing this change.

File: lib/Fragment/Fragment.cpp (hunk 1 above)
Comment (parth-07) [reply lib/Fragment/Fragment.cpp:117]: We cannot use dotSymbol here because the dotSymbol value keeps changing as we perform the layout. If we use `dotSymbol` here, then the `Fragment::getOffset()` will give incorrect results when used outside the layout-iteration context.

File: test/UnitTests/CMakeLists.txt (hunk 2 above)
Comment (parth-07) [reply test/UnitTests/CMakeLists.txt:10]: I have removed this change.

File: lib/Fragment/Fragment.cpp (hunk 1 above)
Comment (quic-seaswara) [reply lib/Fragment/Fragment.cpp:117]: Outside the layout-iteration context, did not think about it!.

We should remove the dependency of the output section and use the owning section address ( all fragments are relative to the owning section right ? ) 

Can you add a test that includes debug sections and check for offset alignments ?

File: lib/Fragment/Fragment.cpp [hunk 3]
```diff
@@ -107,7 +108,14 @@ Fragment *Fragment::getNextNode() {
 size_t Fragment::paddingSize() const {
   if (!hasOffset())
     return 0;
-  return llvm::offsetToAlignment(UnalignedOffset, llvm::Align(Alignment));
+  // FIXME: Will a fragment ever not have an owning section / output section?
+  // We should have linker invariants such as 'All fragments must always have a
+  // fragment' so that we can write codes in a uniform way without having too
+  // many if-checks.
```
Comment (quic-seaswara) [inline lib/Fragment/Fragment.cpp:114]: All fragments definitely have a owning section, cant think of any that does not have one.

File: test/Common/standalone/FragPaddingWithUnalignedOutSect/Inputs/script2.t [hunk 4]
```diff
@@ -0,0 +1,7 @@
+SECTIONS {
+  .text (0x14) : {
+    . = . + 0x2;
```
Comment (quic-seaswara) [inline test/Common/standalone/FragPaddingWithUnalignedOutSect/Inputs/script2.t:3]: There are users such as picolibc that do something like this :

```
        .tbss_space : {
                . = ADDR(.tbss);
                . = . + SIZEOF(.tbss);
        } >ram AT>ram :ram
```

I am pretty sure we dont have a test, but add this test to make sure that we dont regress this.

**Review by quic-seaswara — CHANGES_REQUESTED** [review]

File: lib/Fragment/Fragment.cpp (hunk 1 above)
Comment (parth-07) [reply lib/Fragment/Fragment.cpp:117]: > We should remove the dependency of the output section and use the owning section address ( all fragments are relative to the owning section right ? )

I think with the current design we will need to keep output section dependency. If I understand correctly, then the owning section will refer to the original input section -- we only assign address to the output section, rule sections and fragments.

> Can you add a test that includes debug sections and check for offset alignments ?

Thank you for mentioning debug sections. We often miss testing for debug section offsets. I will add a test for this.

Comment (quic-seaswara) [reply lib/Fragment/Fragment.cpp:117]: we can assign the address to the section as well, and build this feature over the owning section address or punt it after this patch, whatever works is fine. But i feel that we can build over the input section address assignment.

File: lib/Fragment/Fragment.cpp (hunk 3 above)
Comment (parth-07) [reply lib/Fragment/Fragment.cpp:114]: One of the test did fail with a crash due to output section being a nullptr when I did not have these ternary-condition checks. I feel that we need to make the linker invariants more clear and add a mechanism to enforce them. For example, we can use a sentinel `NullOutputSection` in the case when an input section does not have an output section due to an error but we want to continue the link because the user has specified `--no-inhibit-exec`. Please share your thoughts on this.

Comment (quic-seaswara) [reply lib/Fragment/Fragment.cpp:114]: Which test is that ? May be that was called before output sections were set ? 

I think a std::optional would work here instead of NullOutputSection ?

Comment (parth-07) [reply lib/Fragment/Fragment.cpp:114]: > Which test is that ?

I do not recall the name. I will check and update this thread.

> I think a std::optional would work here instead of NullOutputSection ?

I think std::optional will work for most cases, but `--no-inhibit-exec` can create interesting cases where we want to continue link despite the errors. Or in the cases, where we are printing map-file when the link has failed before the link was able to assign an output section to all the input sections.

Comment (parth-07) [reply lib/Fragment/Fragment.cpp:114]: Yes, `std::optional` will work. But then we still need to check if the optional has value or not. We cannot simply call `OutSect->addr()`, we instead need to do `OutSect.has_value() ? (*OutSect).addr() : 0`. It is the same as the pointer case.

Comment (quic-seaswara) [reply lib/Fragment/Fragment.cpp:114]: Good suggestion!

File: test/Common/standalone/FragPaddingWithUnalignedOutSect/Inputs/script2.t (hunk 4 above)
Comment (parth-07) [reply test/Common/standalone/FragPaddingWithUnalignedOutSect/Inputs/script2.t:3]: I tried adding a test for this, but it seems that we have an another bug that causes incorrect `.tbss_space` layout if `.tbss` has an explicit address and a memory region. I have created an issue for this: #367.

I have added tests for checking layout of `.tdata` and `.tbss` fragments when the output section address is unaligned.

File: lib/Fragment/Fragment.cpp (hunk 1 above)
Comment (parth-07) [reply lib/Fragment/Fragment.cpp:117]: > But i feel that we can build over the input section address assignment.

Yes, we can build over the input section address assignment, but I believe that should be handled as an independent refactoring effort to improve the design, as that increases the code changes and testing scope significantly.

Comment (parth-07) [reply lib/Fragment/Fragment.cpp:117]: > Can you add a test that includes debug sections and check for offset alignments ?

I could not add test for debug sections because there is no way to assign explicit address/offset to debug sections and because the debug section alignment is always 1. To test this change, we need to make output section address/offset incongruent to the fragment address/offset (modulo fragment alignment).

Comment (quic-seaswara) [reply lib/Fragment/Fragment.cpp:117]: You can include a debug section in a alloc section, or use SUBALIGN

Comment (parth-07) [reply lib/Fragment/Fragment.cpp:117]: Thank you for the suggestions. I have added a test for the debug section as well.

**Review by quic-seaswara — APPROVED** [review]
