### PR TITLE
[reproduce] Fix response file for namespec-resolved libraries

### LINKED ISSUE #731: reproduce option tarball does not work as expected with shared objects
```
cat > 1.c << \!
int foo() { return 0; }
!

cat > 2.c << \!
int bar() { return 0; }
!

rm -f lib2.* && clang -c -target hexagon -c 2.c
ld.eld -shared 2.o -o lib2.so
clang -c 1.c
ld.eld -Bdynamic 1.o -L. -l2 -o a --reproduce a.tar
```

Extracting the tarball and running the response file, produces an error

```
ld.eld -Bdynamic Object/1.o.6060996770729379307 lib2.so -o a --mapping-file=mapping.ini
Fatal: cannot read file 'lib2.so'
Fatal: Linking had errors.
```

### PR DESCRIPTION
**Pull request by quic-areg**
Libraries passed as -l<name> or -l:<filename> were emitted as a bare basename rather than their tarball path, so relinking from the extracted tarball failed.

Fixes: #731, #747

### CODE REVIEW

File: lib/LinkerWrapper/GnuLdDriver.cpp [hunk 1]
```diff
@@ -1653,7 +1653,13 @@ bool GnuLdDriver::processReproduceOption(
           auto ipt = action->getInput();
           if (!ipt)
             return false;
-          os << outputTar->rewritePath(ipt->getName()) << ' ';
+          // Use the mapped path as the rewrite key. For a namespec input
+          // e.g. "-l2", use "2" instead of "lib2.so". This will match the
```
Comment (quic-seaswara) [inline lib/LinkerWrapper/GnuLdDriver.cpp:1657]: map file needs to be updated too. follow up is ok.

**Review by quic-seaswara — APPROVED** [review]

File: lib/LinkerWrapper/GnuLdDriver.cpp (hunk 1 above)
Comment (quic-areg) [reply lib/LinkerWrapper/GnuLdDriver.cpp:1657]: Updated how?

Comment (quic-seaswara) [reply lib/LinkerWrapper/GnuLdDriver.cpp:1657]:
```
cat > 1.c << \!
int foo() { return 0; }
!

cat > 2.c << \!
int bar() { return 0; }
!

rm -f lib2.* && clang -c -target hexagon -c 2.c
ld.eld -shared 2.o -o lib2.so
clang -c 1.c
ld.eld -Bdynamic 1.o -L /tmp/ -l2 -o a --reproduce a.tar
```

This is what the map file shows with this change

Linker Script and memory map
LOAD 1.o(Object/1.o.12657934096141885456)[x86_64]
LOAD 2(2)[x86_64]

Recommend that 2(2) be expanded to 

-l2 (SharedLibrary/2.x)
