### PR TITLE
Fix SUBALIGN linker script feature

### LINKED ISSUE #343: linkerscript SUBALIGN applies to each input section
SUBALIGN may be used to adjust the alignment of each input section

```
cat > script.t << '!'
SECTIONS {
  text (0x14) : SUBALIGN(64) {
    *(.text*)
  }
}
!

cat > test.c << '!'
int foo() { return 1; }
int bar() { return 0; }
!

clang -falign-functions=4 --target=riscv32-unknown-elf -c test.c -ffunction-sections
ld.eld test.o -T script.t -Map map.txt -o eld.out
```

**Bug** 

```
$ llvm-readelf -s eld.out | grep -E 'foo|bar'
     9: 00000014    18 FUNC    GLOBAL DEFAULT     1 foo
    10: 00000028    18 FUNC    GLOBAL DEFAULT     1 bar
```

**Correct Behavior**

```
$ llvm-readelf -s bfd.out | grep -E 'foo|bar'
     9: 00000040    18 FUNC    GLOBAL DEFAULT     1 foo
    10: 00000080    18 FUNC    GLOBAL DEFAULT     1 bar
```

### PR DESCRIPTION
**Pull request by parth-07**
This commit fixes the SUBALIGN linker script feature. SUBALIGN feature is used to modify the alignment of all input sections present in an output section. Until now, we were only changing the alignment of the first fragment of each rule of the output sections with SUBALIGN specified. This commit fixes the SUBALIGN behavior.

SUBALIGN affects the alignment of the first fragment as is seen by the linker when traversing the output sections for the input sections that may contain more than 1 fragment such as .eh_frame, PLT / GOT sections, and .comment section.

Resolves #343

### CODE REVIEW

File: lib/Object/ObjectLinker.cpp [hunk 1]
```diff
@@ -1291,6 +1295,36 @@ bool ObjectLinker::initializeOutputSectionsAndRunPlugin() {
...
+    }
+
+    // Track input sections seen for this output.
+    static std::unordered_set<ELFSection *> seen;
+
+    for (RuleContainer *R : *O) {
+      ELFSection *InSect = R->getSection();
+      for (Fragment *F : InSect->getFragmentList()) {
+        ELFSection *owningSect = F->getOwningSection();
+        if (owningSect && seen.insert(owningSect).second) {
```
Comment (quic-areg) [inline lib/Object/ObjectLinker.cpp:1378]: early return if either of these are false?

Comment (parth-07) [reply lib/Object/ObjectLinker.cpp:1378]: There is no statement after this if-command, and thus, I am not sure if early return would be beneficial here.

File: lib/Object/ObjectLinker.cpp [hunk 2]
```diff
@@ -1291,6 +1295,33 @@ bool ObjectLinker::initializeOutputSectionsAndRunPlugin() {
...
+  for (auto *O : ThisModule->getScript().sectionMap()) {
+    auto &Prolog = O->prolog();
+    std::optional<uint64_t> optSubAlign;
+    if (Prolog.hasSubAlign()) {
+      Prolog.subAlign().eval();
+      Prolog.subAlign().commit();
+      optSubAlign = Prolog.subAlign().result();
+    }
+
+    for (RuleContainer *R : *O) {
```
Comment (quic-seaswara) [inline lib/Object/ObjectLinker.cpp:1371]: if (!Prolog.hasSubAlign())
   continue;

File: lib/Object/ObjectLinker.cpp [hunk 3]
```diff
@@ -1291,6 +1295,33 @@ bool ObjectLinker::initializeOutputSectionsAndRunPlugin() {
...
+      ELFSection *InSect = R->getSection();
+      for (Fragment *F : InSect->getFragmentList()) {
+        ELFSection *owningSect = F->getOwningSection();
+        if (owningSect && seen.insert(owningSect).second && optSubAlign) {
+          F->setAlignment(optSubAlign.value());
+          InSect->setAddrAlign(
+              std::max(static_cast<uint64_t>(InSect->getAddrAlign()),
+                       optSubAlign.value()));
+        }
```
Comment (quic-seaswara) [inline lib/Object/ObjectLinker.cpp:1388]: Can we do this at the time of calling mergeSections.

I would think we would implement by first 

- inspecting if the output section has subalign 
- update rule container with the maximum alignment of the section

File: lib/Object/ObjectLinker.cpp [hunk 4]
```diff
@@ -1291,6 +1295,33 @@ bool ObjectLinker::initializeOutputSectionsAndRunPlugin() {
...
+      optSubAlign = Prolog.subAlign().result();
+    }
+
+    for (RuleContainer *R : *O) {
+      ELFSection *InSect = R->getSection();
+      for (Fragment *F : InSect->getFragmentList()) {
+        ELFSection *owningSect = F->getOwningSection();
+        if (owningSect && seen.insert(owningSect).second && optSubAlign) {
+          F->setAlignment(optSubAlign.value());
+          InSect->setAddrAlign(
```
Comment (quic-seaswara) [inline lib/Object/ObjectLinker.cpp]: Should we emit a warning for sections that bumping subalign can cause issues 

Examples of them may be dynamic sections or eh frame sections.

File: lib/Object/ObjectLinker.cpp (hunk 3 above)
Comment (quic-seaswara) [reply lib/Object/ObjectLinker.cpp:1388]: You might want also want to make sure the map file is annotated with this information for debugging reasons.

File: lib/Object/ObjectLinker.cpp (hunk 2 above)
Comment (parth-07) [reply lib/Object/ObjectLinker.cpp:1371]: We cannot skip output sections that do not have `SUBALIGN`. The way we define `SUBALIGN` functionality in eld is: subalign changes the alignment of the fragments in the output sections that are the first fragments **seen from their corresponding input sections.** in the output section table.

So, if a plugin moves fragments of a section into two output sections, we need to determine which of them appears first in the output section table, and thus we need to go through all the output sections and fragments.

File: lib/Object/ObjectLinker.cpp (hunk 3 above)
Comment (parth-07) [reply lib/Object/ObjectLinker.cpp:1388]: > Can we do this at the time of calling mergeSections.

merging input sections handles entirely different responsibility than handling subAlign. Why should we do this together with merging input sections? I would like to follow the unix philosophy, "do one thing well", wherever possible.

> You might want also want to make sure the map file is annotated with this information for debugging reasons.

I will add map-file improvements as a follow-up patch.

File: lib/Object/ObjectLinker.cpp (hunk 4 above)
Comment (parth-07) [reply lib/Object/ObjectLinker.cpp]: I am not aware of cases where making alignment larger can cause issues. Why would increasing alignment of .dynamic / .eh_frame sections cause issues?

I think we should emit warning if subalign is used to decrease the alignment of an input section.

File: lib/Object/ObjectLinker.cpp (hunk 3 above)
Comment (quic-seaswara) [reply lib/Object/ObjectLinker.cpp:1388]: Merging input sections already takes care of choosing the maximum alignment, and SUBALIGN is just one additional kind for choosing maximum alignment.

I am very concerned about link time. 

* The usage of subalign is very rare and we are iterating through all the output sections for rare use-cases. 
* We can mention as undefined behavior for now if users use SUBALIGN with linker plugin chunk movements. 

Independent of the current approach, this patch traverses through every output section (allocatable, non allocatable sections), which can be improved too. 

Overall comment : If you are covering some use-case, please add tests for all use cases. 

For example 

* DISCARD sections
* Emit relocs 
* Empty sections with SUBALIGN, Sections with explicit data - BYTE/QUAD/... 
* Partial linking
* Shared libraries 
* Non allocatable sections (probably we should warn here and not do anything)

Comment (quic-seaswara) [reply lib/Object/ObjectLinker.cpp:1388]: I feel like map file improvements need to go in the same patch just because it would be a way to check of what the linker did explicitly.

Comment (parth-07) [reply lib/Object/ObjectLinker.cpp:1388]: > Merging input sections already takes care of choosing the maximum alignment, and SUBALIGN is just one additional kind for choosing maximum alignment.

Merging input sections only sets the alignment of the rule-container internal input section, it is not responsible of reading linker script directives to change the alignments and it does not change the alignment of fragments / owning input sections.

> I am very concerned about link time.

The link time would be the same whether we apply subalign alignments as part of the merging input sections, or
as a separate step after it. This is because the number of operations remains the same.

> The usage of subalign is very rare and we are iterating through all the output sections for rare use-cases.

It is one pass over the fragments. We have many such passes over the fragments. I do not expect to see any noticeable
time difference. Do you think it would be better to go over the output sections once and check whether there is any output section with subalign, and only traverse fragments if there is indeed a use of subalign in the link?

We can change the code to **only traverse fragments of output sections with SUBALIGN** but that will slightly change the meaning of SUBALIGN for us. Please let me know if that would be fine. 

> We can mention as undefined behavior for now if users use SUBALIGN with linker plugin chunk movements.

Disabling plugin chunk movements depending upon whether SUBALIGN is used or not seems to be a very big restriction to me, and I believe that we should avoid it if possible. Additionally, even without the SUBALIGN, if plugins move the fragments incorrectly, then the image will be invalid and we do not report any warning / error for it.

> Independent of the current approach, this patch traverses through every output section (allocatable, non allocatable sections), which can be improved too.
> Overall comment : If you are covering some use-case, please add tests for all use cases.

I will add more tests, but I think as a functionality-wise, `SUBALIGN` should work for all the output sections. Other similar linker script functionality such as output section alignment can be specified for all the outputs sections as well.

Comment (quic-seaswara) [reply lib/Object/ObjectLinker.cpp:1388]: yes, that is what I am trying to say do this only for output sections with SUBALIGN. 

Restrict plugins to not move chunks between output sections with SUBALIGN. This is totally ok for me. We can relax this case if we have a genuine requirement. 

It does not make sense to use SUBALIGN on sections such as debug. We should warn on those usecases.

Comment (parth-07) [reply lib/Object/ObjectLinker.cpp:1388]: > yes, that is what I am trying to say do this only for output sections with SUBALIGN.

I have changed the code to iterate input sections of only output sections that have SUBALIGN.

> Restrict plugins to not move chunks between output sections with SUBALIGN. This is totally ok for me. We can relax this case if we have a genuine requirement.

The issue of incorrectly moving chunks of the same input section is not limited to SUBALIGN usage. If a plugin moves the chunk of the same input section to different output sections, then the image would be wrong even with no SUBALIGN usage.

> It does not make sense to use SUBALIGN on sections such as debug. We should warn on those usecases.

Can we add handle such diagnostic improvements separately? Also, I believe that if there is no harm on using SUBALIGN for non-alloc sections, then we do not need to report a warning for it. We do not report any warning for using ALIGN on non-alloc sections as well.

Comment (parth-07) [reply lib/Object/ObjectLinker.cpp:1388]: > For example
>DISCARD sections
> Emit relocs
> Empty sections with SUBALIGN, Sections with explicit data - BYTE/QUAD/...
> Partial linking
> Shared libraries
> Non allocatable sections

I have added tests for all these cases. I am not currently warning for non-allocatable sections because we also do not warn if `ALIGN` linker script directive or the output section address linker script directive is used on non-allocatable sections.

I have added a test and a diagnostic for when SUBALIGN reduces an input section alignment.

File: include/eld/Diagnostics/DiagLDScript.inc [hunk 5]
```diff
@@ -122,6 +122,8 @@ DIAG(error_cannot_specify_lma_and_memory_region, DiagnosticEngine::Error,
      "cannot specify AT and LMA memory region for output section : %0 defined in script %1")
 DIAG(warn_non_power_of_2_value_to_align_builtin, DiagnosticEngine::Warning,
      "%0: non-power-of-2 value 0x%1 passed to ALIGN builtin function")
+DIAG(warn_subalign_less_than_section_alignment, DiagnosticEngine::Warning,
+     "SUBALIGN(0x%0) is less than section alignment (0x%1) for section '%2'")
```
Comment (quic-seaswara) [inline include/eld/Diagnostics/DiagLDScript.inc]: Add the input file as well.

File: lib/Object/ObjectLinker.cpp [hunk 6]
```diff
@@ -1329,6 +1319,41 @@ bool ObjectLinker::initializeOutputSectionsAndRunPlugin() {
   return runOutputSectionIteratorPlugin();
 }
 
+void ObjectLinker::applySubAlign() {
+  std::unordered_set<ELFSection *> seen;
```
Comment (quic-seaswara) [inline lib/Object/ObjectLinker.cpp:1360]: This variable can moved to line 1329 ?

File: lib/Object/ObjectLinker.cpp [hunk 7]
```diff
@@ -1329,6 +1319,41 @@ bool ObjectLinker::initializeOutputSectionsAndRunPlugin() {
...
+      ELFSection *inSect = R->getSection();
+      for (Fragment *F : inSect->getFragmentList()) {
+        ELFSection *owningSect = F->getOwningSection();
+        if (owningSect->getKind() == LDFileFormat::Kind::OutputSectData) {
+          continue;
+        }
+        if (owningSect && seen.insert(owningSect).second) {
+          // Warn if SUBALIGN is reducing the section alignment
+          if (ThisConfig.showLinkerScriptWarnings() && F->alignment() > subAlign) {
+            ThisConfig.raise(Diag::warn_subalign_less_than_section_alignment)
```
Comment (quic-seaswara) [inline lib/Object/ObjectLinker.cpp:1381]: Should this be an error ?

File: lib/Object/ObjectLinker.cpp [hunk 8]
```diff
@@ -1329,6 +1319,41 @@ bool ObjectLinker::initializeOutputSectionsAndRunPlugin() {
   return runOutputSectionIteratorPlugin();
 }
 
+void ObjectLinker::applySubAlign() {
+  std::unordered_set<ELFSection *> seen;
+
+  for (auto *O : ThisModule->getScript().sectionMap()) {
```
Comment (quic-seaswara) [inline lib/Object/ObjectLinker.cpp:1362]: follow up : multithread by output section

File: lib/Object/ObjectLinker.cpp (hunk 3 above)
Comment (quic-seaswara) [reply lib/Object/ObjectLinker.cpp:1388]: I agree we dont do this, but its an area that we can make the user understand what he might be doing or improve his build.

We should try and improve, but I agree this can be a follow up too.

File: lib/Object/ObjectLinker.cpp [hunk 9]
```diff
@@ -1329,6 +1319,41 @@ bool ObjectLinker::initializeOutputSectionsAndRunPlugin() {
...
+    prolog.subAlign().eval();
+    prolog.subAlign().commit();
+    subAlign = prolog.subAlign().result();
+
+    for (RuleContainer *R : *O) {
+      ELFSection *inSect = R->getSection();
+      for (Fragment *F : inSect->getFragmentList()) {
+        ELFSection *owningSect = F->getOwningSection();
+        if (owningSect->getKind() == LDFileFormat::Kind::OutputSectData) {
+          continue;
```
Comment (quic-seaswara) [inline lib/Object/ObjectLinker.cpp:1376]: awesome!

Should we do this for internal sections ?

File: lib/Object/ObjectLinker.cpp (hunk 8 above)
Comment (parth-07) [reply lib/Object/ObjectLinker.cpp:1362]: We cannot do this computation multi-threaded, otherwise the subalign behavior will become non-deterministic for the input sections which consist of multiple fragments.

File: lib/Object/ObjectLinker.cpp (hunk 6 above)
Comment (parth-07) [reply lib/Object/ObjectLinker.cpp:1360]: No, it has to be before the `for (auto : sectionMap())` loop

File: lib/Object/ObjectLinker.cpp (hunk 7 above)
Comment (parth-07) [reply lib/Object/ObjectLinker.cpp:1381]: No, as per GNU ld docs (https://sourceware.org/binutils/docs/ld/Forced-Input-Alignment.html), SUBALIGN is allowed to reduce the input section alignment.

File: lib/Object/ObjectLinker.cpp (hunk 9 above)
Comment (parth-07) [reply lib/Object/ObjectLinker.cpp:1376]: We may need to take this as case-by-case basis. Most internal sections do indeed represent a section and thus `SUBALIGN` should affect them. `OutputSectData` is an exception because it is not a section at all as per GNU ld docs.

File: include/eld/Diagnostics/DiagLDScript.inc (hunk 5 above)
Comment (parth-07) [reply include/eld/Diagnostics/DiagLDScript.inc]: Thank you for the suggestion. I have improved this diagnostic.

File: include/eld/Diagnostics/DiagLDScript.inc [hunk 10]
```diff
@@ -122,6 +122,8 @@ DIAG(error_cannot_specify_lma_and_memory_region, DiagnosticEngine::Error,
      "cannot specify AT and LMA memory region for output section : %0 defined in script %1")
 DIAG(warn_non_power_of_2_value_to_align_builtin, DiagnosticEngine::Warning,
      "%0: non-power-of-2 value 0x%1 passed to ALIGN builtin function")
+DIAG(warn_subalign_less_than_section_alignment, DiagnosticEngine::Warning,
+     "SUBALIGN(0x%0) is less than the section alignment (0x%1) for section '%2(%3)'")
```
Comment (quic-areg) [inline include/eld/Diagnostics/DiagLDScript.inc]: can we use `ELFSection::getLocation` for diagnostics for sections? it will conveniently print the input file too, and section offset in hex if any

Comment (parth-07) [reply include/eld/Diagnostics/DiagLDScript.inc]: Thank you for the suggestion. I have changed the code to use `ELFSection::getLocation`

File: lib/Object/ObjectLinker.cpp [hunk 11]
```diff
@@ -1356,6 +1346,41 @@ bool ObjectLinker::initializeOutputSectionsAndRunPlugin() {
...
+        }
+        if (owningSect && seen.insert(owningSect).second) {
+          // Warn if SUBALIGN is reducing the section alignment
+          if (ThisConfig.showLinkerScriptWarnings() && F->alignment() > subAlign) {
+            ThisConfig.raise(Diag::warn_subalign_less_than_section_alignment)
+                << utility::toHex(subAlign) << utility::toHex(F->alignment())
+                << owningSect->getLocation(0, ThisConfig.options());
+          }
+          F->setAlignment(subAlign);
```
Comment (quic-seaswara) [inline lib/Object/ObjectLinker.cpp:1385]: We should do 

F->setOwningSection->setAlignment(subAlign)  right ?

Comment (partaror) [reply lib/Object/ObjectLinker.cpp:1385]: No. `Fragment::paddingSize()` is the key function that determines a fragment's padding requirements and it uses Fragment's alignment instead of the owning input section alignment. In the current design, it seems that we prefer fragment's alignment over the input section's alignment in the layout phase.
