### PR TITLE
Recompute layout until symbol values converge

### LINKED ISSUE #943: Incorrect symbol value due to forward reference in linker script
We may observe incorrect symbol values due to forward references in linker script. This can issues as incorrect relaxations. 

Reproducer:

```bash
#!/usr/bin/env bash

cat >1.c <<\EOF
int foo() { return 1; }
int u = 3;
EOF

cat >script.t <<\EOF
SECTIONS {
  .text : { *(.text*) }
  .data : { *(.data*) }
  .comment : { *(.comment*) }
  a = b + c;
  b = c + 0x100;
  c = 0x1000;
}
EOF


clang -o 1.o -target aarch64-linux-gnu 1.c -c
LDs=(ld.eld ld.lld aarch64-none-linux-gnu-ld.bfd)
SFs=(eld lld bfd)

for i in "${!SFs[@]}"; do
  ${LDs[$i]} -o 1.${SFs[$i]}.out 1.o -T script.t
  llvm-readelf -s 1.${SFs[$i]}.out | grep 'ABS a'
done
```

Output:
```
13: 0000000000001100     0 NOTYPE  GLOBAL DEFAULT   ABS a
ld.lld: warning: cannot find entry symbol _start; not setting start address
    10: 0000000000002100     0 NOTYPE  GLOBAL DEFAULT   ABS a
aarch64-none-linux-gnu-ld.bfd: warning: 1.bfd.out has a LOAD segment with RWX permissions
    13: 0000000000002100     0 NOTYPE  GLOBAL DEFAULT   ABS a
```

eld generated executable has incorrect value for the symbol `a`, `1100` instead of the `2100`.

### PR DESCRIPTION
**Pull request by parth-07**
This commit modifies the layout step to recompute layout until the symbol values converge. The reiteration has an upper-limit of 4. On reaching this limit, a note is emitted and layout reiteration is stopped.

Please note that this reiteration limit is for layout iterations before relaxations take place. After a layout relaxation pass, the reiteration count is reset to 0.

Resolves #943

### CODE REVIEW

File: lib/Target/GNULDBackend.cpp [hunk 1]
```diff
@@ -3292,25 +3293,68 @@ GNULDBackend::LayoutSnapshot GNULDBackend::captureLayoutSnapshot() const {
...
   return S;
 }
 
-const OutputSectionEntry *
+std::vector<const LDSymbol *> GNULDBackend::collectScriptDefinedSymbols() const {
+  std::vector<const LDSymbol *> Result;
+  const llvm::StringMap<ResolveInfo *> &Globals =
+      m_Module.getNamePool().getGlobals();
+  for (const auto &Entry : Globals) {
+    const ResolveInfo *RI = Entry.second;
```
Comment (quic-seaswara) [inline lib/Target/GNULDBackend.cpp]: We should not be comparing the symbol values of global symbols, as you can clearly see that local symbols are missing. 

Can we check for fragment address instead ?

File: lib/Target/GNULDBackend.cpp [hunk 2]
```diff
@@ -3292,25 +3293,68 @@ GNULDBackend::LayoutSnapshot GNULDBackend::captureLayoutSnapshot() const {
...
+    ASSERT(RI, "Must not be null!");
```
Comment (quic-seaswara) [inline lib/Target/GNULDBackend.cpp]: Is this assert needed ?

File: include/eld/Target/GNULDBackend.h [hunk 3]
```diff
@@ -771,13 +771,31 @@ class GNULDBackend {
 
   struct LayoutSnapshot {
     llvm::DenseMap<const OutputSectionEntry *, SectionAddrs> outSections;
+    llvm::DenseMap<const LDSymbol *, uint64_t> symbolValues;
   };
 
-  // Capture current layout snapshot keyed by OutputSectionEntry*.
-  LayoutSnapshot captureLayoutSnapshot() const;
+  struct DivergenceResult {
+    const OutputSectionEntry *section = nullptr;
```
Comment (quic-seaswara) [inline include/eld/Target/GNULDBackend.h]: section -> output section

File: lib/Target/GNULDBackend.cpp [hunk 4]
```diff
@@ -3292,25 +3293,68 @@ GNULDBackend::LayoutSnapshot GNULDBackend::captureLayoutSnapshot() const {
...
+    if (!RI->outSymbol())
+      continue;
+    const LDSymbol *Sym = RI->outSymbol();
+    if (Sym->scriptDefined())
+      Result.push_back(Sym);
```
Comment (quic-seaswara) [inline lib/Target/GNULDBackend.cpp]: It would be useful to show the expression in the diagnostic instead of symbol, that will allow users do diagnose the problem better.

File: lib/Target/GNULDBackend.cpp [hunk 5]
```diff
@@ -3292,25 +3293,68 @@ GNULDBackend::LayoutSnapshot GNULDBackend::captureLayoutSnapshot() const {
...
+  }
+  return Result;
+}
+
+void GNULDBackend::captureSymbolsSnapshot(
+    LayoutSnapshot &S,
+    const std::vector<const LDSymbol *> &ScriptDefinedSymbols) const {
+  for (const LDSymbol *Sym : ScriptDefinedSymbols)
+    S.symbolValues.insert({Sym, Sym->value()});
```
Comment (quic-seaswara) [inline lib/Target/GNULDBackend.cpp]: Does this work for provide as well ? because the symbols are not defined

File: lib/Target/GNULDBackend.cpp [hunk 6]
```diff
@@ -4123,17 +4170,19 @@ bool GNULDBackend::relax() {
...
-      if (changed) {
-        // Emit a note for the first observed changed section.
-        if (const ELFSection *S = changed->getSection())
+      if (diverged.section) {
+        if (const ELFSection *S = diverged.section->getSection())
           config().raise(Diag::note_section_address_not_converging)
               << S->name() << maxIterations;
+      } else if (diverged.symbol) {
+        config().raise(Diag::note_symbol_value_not_converging)
+            << diverged.symbol->name() << maxIterations;
```
Comment (quic-seaswara) [inline lib/Target/GNULDBackend.cpp]: print the symbol, section information and the input file/ input linker script

File: lib/Target/GNULDBackend.cpp (hunk 1 above)
Comment (parth-07) [reply lib/Target/GNULDBackend.cpp]: I thought about it. I believe that just comparing the linker script symbols is enough. If all the linker script symbols and the output section address converge, then all the section-relative symbols will also converge. Please let me know your thoughts on this.

Comment (quic-seaswara) [reply lib/Target/GNULDBackend.cpp]: interesting observation. Would this capture bumping alignment using dot inside output sections ?

Comment (parth-07) [reply lib/Target/GNULDBackend.cpp]: >Would this capture bumping alignment using dot inside output sections ?
> It would be useful to show the expression in the diagnostic instead of symbol, that will allow users do diagnose the problem better.

Thank you for these comments. I thought more about it. If we ensure that linker script symbols values converge after layout passes, then for most cases dot assignments within output section would converge as well. However, it is possible that due to corner cases / layout issues, the final value of a symbol is converging but the intermittent value is not. 

It would be much better to ensure that the assignments result converge instead of linker script values converge. This will capture the symbol intermediate values case as well. Additionally, it would make it possible to pin-point the exact expression where non-convergence is happening -- something that we cannot do if we only compare symbol values. Please let me know your thoughts on this.

File: lib/Target/GNULDBackend.cpp (hunk 5 above)
Comment (parth-07) [reply lib/Target/GNULDBackend.cpp]: Yes, it works with PROVIDE as well. Provide symbols are handled / included much before the layout starts.

File: lib/Target/GNULDBackend.cpp (hunk 1 above)
Comment (parth-07) [reply lib/Target/GNULDBackend.cpp]: I have changed the design to use assignments instead of symbols to check layout convergence based on our offline discussion.

File: include/eld/Target/GNULDBackend.h (hunk 3 above)
Comment (parth-07) [reply include/eld/Target/GNULDBackend.h]: Done.

File: lib/Target/GNULDBackend.cpp (hunk 4 above)
Comment (parth-07) [reply lib/Target/GNULDBackend.cpp]: Done. Now the diagnostic show the exact assignment that is non-converging.

File: lib/Target/GNULDBackend.cpp (hunk 6 above)
Comment (parth-07) [reply lib/Target/GNULDBackend.cpp]: I have added the assignment dump and the input linker script information here.

File: lib/Target/GNULDBackend.cpp (hunk 2 above)
Comment (parth-07) [reply lib/Target/GNULDBackend.cpp]: I used the assert as a safety check for nulls. I was not sure if it is really required. This code has been removed as it is not required in the updated design in which we use assignment values instead of symbol values for determining convergence.
