### PR TITLE
[ARM][AArch64] Fix computation of local-exec TLS relocations

### LINKED ISSUE #302: Incorrect offsets for TLS accesses on AArch64
picolibc's TLS tests (https://github.com/picolibc/picolibc/blob/main/test/tls.c) are currently failing when built with eld. I think this is due to incorrect offsets being used when accessing TLS variables where other TLS variables with sufficiently large alignments are present.

It looks like eld is always using a 16-byte offset (for the TCB I guess) rather than also accounting for possible alignment padding which is what lld/bfd/picolibc all seem to be doing or expecting. I'm not sure what the official source is, but a few possibly-relevant snippets from codebases about this:
* lld: https://github.com/llvm/llvm-project/blob/4c2d56318fec16d1d5241cd91d38b59cb65bce83/lld/ELF/InputSection.cpp#L726-L729
* picolibc: https://github.com/picolibc/picolibc/blob/c623d2b6001f41e2d5bfcd91943ff1ead960f3d5/picolibc.ld.in#L271C6-L271C74 and https://github.com/picolibc/picolibc/blob/c623d2b6001f41e2d5bfcd91943ff1ead960f3d5/picocrt/machine/aarch64/crt0.c#L60

**Reproducer**
This isn't exactly a full running/working reproducer, but is hopefully sufficient. picolibc's test is a full running example too
```
cat > test.c << '!'
__thread int a = 12;
__attribute__((aligned(128)))
__thread int b = 13;

int foo(void) { return a; }
!

clang --target=aarch64-none-elf -c test.c
ld.eld -maarch64linux test.o -o eld.a.out
ld.lld test.o -o lld.a.out
ld.bfd test.o -o bfd.a.out
```

**Output**
```
eld:
  400120: d53bd048      mrs     x8, TPIDR_EL0
  400124: 91400108      add     x8, x8, #0x0, lsl #12   // =0x0
  400128: 91004108      add     x8, x8, #0x10

lld/bfd (output snippet here is effectively the same between the two linkers, just different addresses):
  2101c8: d53bd048      mrs     x8, TPIDR_EL0
  2101cc: 91400108      add     x8, x8, #0x0, lsl #12   // =0x0
  2101d0: 91020108      add     x8, x8, #0x80
```

### PR DESCRIPTION
**Pull request by parth-07**
This commit fixes computation of local-exec TLS relocations for
ARM and AArch64. Previously, we were not using the correct start offset
in static thread local storage block for computing the relocation.

Lets understand this with the help of an example

```

             <--------- Static thread local storage block  ------------------>
| --------- | ----------------- | --------------------- | ----------------------- |
     TCB    TP  Reserved space      Alignment padding      Thread variables

```
ARM/AArch64 local-exec relocation resolves to:
  SymbolValueInTLSSegment + Reserved Space + Alignment padding

Previously, we were not accounting for the alignment padding. But why is
this alignment padding required? It is required so that the symbol
alignments assumed at the compile/link time is satisfied at runtime as
well. The exact condition that should be satisfied is:

&nbsp;&nbsp; VMA(TP) + Reserved space + Alignment padding congruent to TLSSegment[vaddr] (modulo TLSSegment[align])

This condition becomes more clear with the help of an example:

&nbsp;&nbsp;  StartVMAForStaticThreadVariables = VMA(TP) + Reserved space + Alignment padding

&nbsp;&nbsp;  StartVMAForStaticThreadVariables should be congruent to TLSSegment[vaddr] (modulo TLSSegment[align])

Resolves #302

### CODE REVIEW

File: lib/Target/AArch64/AArch64Relocator.cpp [hunk 1]
```diff
@@ -1031,7 +1031,21 @@ Relocator::Result tls_gottprel_lo(Relocation &pReloc,
...
+  auto OptMaxTLSSegAlignment = pParent.getMaxTLSSegmentAlign();
+  if (!OptFirstTLSSegVirtualAddr.has_value() ||
+      !OptMaxTLSSegAlignment.has_value()) {
+    pParent.config().raise(Diag::no_pt_tls_segment);
+    return Relocator::Result::BadReloc;
+  }
+
+  auto FirstTLSSegVirtualAddr = OptFirstTLSSegVirtualAddr.value();
+  auto MaxTLSSegAlignment = OptMaxTLSSegAlignment.value();
+  X += ((FirstTLSSegVirtualAddr - 2 * WordSize) & (MaxTLSSegAlignment - 1));
```
Comment (quic-seaswara) [inline lib/Target/AArch64/AArch64Relocator.cpp]: This can go to AArch64Relocator, less duplication of code

File: lib/Target/ARM/ARMRelocator.cpp [hunk 2]
```diff
@@ -1590,9 +1590,21 @@ Relocator::Result tls_ldo32(Relocation &pReloc, ARMRelocator &pParent) {
...
+  auto OptMaxTLSSegAlignment = pParent.getMaxTLSSegmentAlign();
+  if (!OptFirstTLSSegVirtualAddr.has_value() ||
+      !OptMaxTLSSegAlignment.has_value()) {
+    pParent.config().raise(Diag::no_pt_tls_segment);
+    return Relocator::Result::BadReloc;
+  }
+  auto FirstTLSSegVirtualAddr = OptFirstTLSSegVirtualAddr.value();
+  auto MaxTLSSegAlignment = OptMaxTLSSegAlignment.value();
+  pReloc.target() +=
+      ((FirstTLSSegVirtualAddr - 2 * WordSize) & (MaxTLSSegAlignment - 1));
```
Comment (quic-seaswara) [inline lib/Target/ARM/ARMRelocator.cpp]: This also affects other models IE, LD and GD. 

It makes sense to add a function getTLSOffset() in AArch64Relocator.

File: lib/Target/Relocator.cpp [hunk 3]
```diff
@@ -294,3 +295,22 @@ Relocation::Address Relocator::getSymValue(const Relocation *R) {
     return getTarget().finalizeTLSSymbol(R->symInfo()->outSymbol());
   return R->symValue(m_Module);
 }
+
+std::optional<uint64_t> Relocator::getFirstTLSSegmentVirtualAddr() const {
+  const auto &ELFSegTable = getTarget().elfSegmentTable();
+  const auto &TLSSegments = ELFSegTable.getSegments(llvm::ELF::PT_TLS);
```
Comment (quic-seaswara) [inline lib/Target/Relocator.cpp:301]: Can we cache the pointer to the PT_TLS segment in GNULDBackend instead of getting the segments all the time.

**Review by quic-seaswara — COMMENTED** [review]
Please add tests

File: lib/Target/Relocator.cpp (hunk 3 above)
Comment (parth-07) [reply lib/Target/Relocator.cpp:301]: We cannot cache PT_TLS segment in GNULDBackend as there can be multiple relevant PT_TLS segment, but we can cache the FirstTLSSegmentVirtualAddress and MaxTLSSegmentAlignment. I am changing the code to cache these two values.

Comment (quic-seaswara) [reply lib/Target/Relocator.cpp:301]: You can store the cache the TLS segments as a vector in GNULDBackend.

File: lib/Target/ARM/ARMRelocator.cpp (hunk 2 above)
Comment (parth-07) [reply lib/Target/ARM/ARMRelocator.cpp]: It seems that the other models except local-exec does not access static thread local storage block.

File: lib/Target/Relocator.cpp (hunk 3 above)
Comment (quic-seaswara) [reply lib/Target/Relocator.cpp:301]: Thanks!

File: lib/Target/AArch64/AArch64Relocator.cpp (hunk 1 above)
Comment (parth-07) [reply lib/Target/AArch64/AArch64Relocator.cpp]: I have modified the code such that we do not compute TLS offset for each relocation.

File: lib/Target/Relocator.cpp (hunk 3 above)
Comment (parth-07) [reply lib/Target/Relocator.cpp:301]: We now compute TLS offset only once, thus, we do not make so many calls to `ELFSegTable.getSegments(llvm::ELF::PT_TLS)`. I have avoided caching TLS segment variables because I believe the gain is not too much now, and I was worried that we may accidentally use stale value of cached TLS segments at someplace.

File: lib/Target/AArch64/AArch64Relocator.h [hunk 4]
```diff
@@ -75,6 +75,12 @@ class AArch64Relocator : public Relocator {
   void partialScanRelocation(Relocation &pReloc,
                              const ELFSection &pSection) override;
 
+  void computeTLSOffsets() override;
+
+  std::optional<uint64_t> getStaticTLSBlcokVarOffset() const {
```
Comment (quic-seaswara) [inline lib/Target/AArch64/AArch64Relocator.h]: nit: getStaticTLSBlock

File: lib/Target/Relocator.cpp [hunk 5]
```diff
@@ -294,3 +295,22 @@ Relocation::Address Relocator::getSymValue(const Relocation *R) {
...
+  if (TLSSegments.empty())
+    return std::nullopt;
+  return TLSSegments[0]->vaddr();
```
Comment (quic-seaswara) [inline lib/Target/Relocator.cpp:304]: This function should live in GNULDBackend

File: lib/Target/Relocator.cpp [hunk 6]
```diff
@@ -294,3 +295,22 @@ Relocation::Address Relocator::getSymValue(const Relocation *R) {
...
+std::optional<uint64_t> Relocator::getMaxTLSSegmentAlign() const {
+  const auto &ELFSegTable = getTarget().elfSegmentTable();
+  const auto &TLSSegments = ELFSegTable.getSegments(llvm::ELF::PT_TLS);
+  if (TLSSegments.empty())
+    return std::nullopt;
+  uint64_t TLSAlign = 0;
+  for (const auto &S : TLSSegments)
+    TLSAlign = std::max(TLSAlign, S->align());
+  return TLSAlign;
+}
```
Comment (quic-seaswara) [inline lib/Target/Relocator.cpp:316]: This function too should live in GNULDBackend

File: test/AArch64/standalone/TLSLocalExec/TLSLocalExec.test [hunk 7]
```diff
@@ -0,0 +1,15 @@
+#---TLSLocalExec.test--------------------------- PartialLink -----------------#
+#BEGIN_COMMENT
+# This tests checks that eld correctly computes TLS local-exec
+# relocation computation when the TLS segment alignment is greater
+# than 16.
+#END_COMMENT
+#START_TEST
+RUN: %clang %clangopts -o %t1.1.o %p/Inputs/1.c -c
+RUN: %link %linkopts -o %t1.1.out %t1.1.o --defsym __aeabi_read_tp=0
```
Comment (quic-seaswara) [inline test/AArch64/standalone/TLSLocalExec/TLSLocalExec.test]: Need test with linker script too

File: test/ARM/standalone/TLSLocalExec/TLSLocalExec.test [hunk 8]
```diff
@@ -0,0 +1,15 @@
+#---TLSLocalExec.test--------------------------- PartialLink -----------------#
+#BEGIN_COMMENT
+# This tests checks that eld correctly computes TLS local-exec
+# relocation computation when the TLS segment alignment is greater
+# than 16.
+#END_COMMENT
+#START_TEST
+RUN: %clang %clangopts -o %t1.1.o %p/Inputs/1.c -c
+RUN: %link %linkopts -o %t1.1.out %t1.1.o --defsym __aeabi_read_tp=0
```
Comment (quic-seaswara) [inline test/ARM/standalone/TLSLocalExec/TLSLocalExec.test:9]: Same here need test with linker script too

Comment (quic-seaswara) [reply test/ARM/standalone/TLSLocalExec/TLSLocalExec.test:9]: add tests like the below using explicit linker script ALIGN's /SUBALIGN that change the alignment of the section.

I have a thought that the computeTLSOffsets is happening too early

**Review by quic-seaswara — CHANGES_REQUESTED** [review]

**Comment by quic-akaryaki** [comment]
Is this problem specific to aarch64?

**Comment by quic-seaswara** [comment]
> Is this problem specific to aarch64?

ARM/AArch64

File: lib/Target/AArch64/AArch64Relocator.h (hunk 4 above)
Comment (parth-07) [reply lib/Target/AArch64/AArch64Relocator.h]: I do not want to name it getStaticTLSBlock because that would be misleading. Static TLS block contains 2 reserved word bytes, padding alignment, and then TLS data. I want this variable to indicate that it contains the offset to the TLS data/variables inside the static TLS block.

File: lib/Target/Relocator.cpp (hunk 5 above)
Comment (parth-07) [reply lib/Target/Relocator.cpp:304]: This function is currently not required in GNULDBackend. GNULDBackend is more accessible than Relocator. I want to keep the functionality close / restricted to where it is required. Can we please move it to GNULDBackend later when it seems that a similar feature is required at other places too?

File: lib/Target/Relocator.cpp (hunk 6 above)
Comment (parth-07) [reply lib/Target/Relocator.cpp:316]: Can we please move it to GNULDBackend later when it seems that a similar feature is required at other places too?

File: lib/Target/AArch64/AArch64Relocator.h (hunk 4 above)
Comment (quic-seaswara) [reply lib/Target/AArch64/AArch64Relocator.h]: I meant there is a spell check error here 

getStaticTLSBlcokVarOffset -> getStaticBlockVarOffset

File: lib/Target/Relocator.cpp (hunk 5 above)
Comment (quic-seaswara) [reply lib/Target/Relocator.cpp:304]: This should really live in GNULDBackend. We can move it later too.

File: test/ARM/standalone/TLSLocalExec/TLSLocalExec.test (hunk 8 above)
Comment (parth-07) [reply test/ARM/standalone/TLSLocalExec/TLSLocalExec.test:9]: I have add more tests.

**Review by quic-seaswara — APPROVED** [review]
