### PR TITLE
Correct sysroot-prepend conditions for script inputs

### LINKED ISSUE #786: eld looks for version scripts with an absolute path inside of the --sysroot dir
**Description**
When eld is given `--sysroot=/some/dir` and `--version-script=/some/absolute/path` it looks for the file at `/some/dir/some/absolute/path`. In my particular case (cross compiling hwasan with eld, see below), this gives errors. From what I can see, lld and bfd both look into '/some/absolute/path' rather than prepending the sysroot like eld.

**Reproducer**
It's a bit of a silly/incomplete example, but below should work to reproduce the issue.

A real example in the wild can be seen when trying to build hwasan using eld (https://github.com/qualcomm/cpullvm-toolchain/pull/134, logs are [here](https://productionresultssa14.blob.core.windows.net/actions-results/82aa121c-080c-4840-a861-e96cb99a8c80/workflow-job-run-c61aff6f-f8f4-5291-b017-f30f0283516a/logs/job/job-logs.txt?rsct=text%2Fplain&se=2026-02-05T02%3A45%3A20Z&sig=DKKFqQ%2B2mrJ%2F1i9Uu0knLErk8MGOYKkr1Oi49QLQZGE%3D&ske=2026-02-05T05%3A07%3A47Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2026-02-05T01%3A07%3A47Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2025-11-05&sp=r&spr=https&sr=b&st=2026-02-05T02%3A35%3A15Z&sv=2025-11-05))
```
cat > empty.c << '!'
int main() {}
!
touch myvers.vers

# eld errors with the below when given an absolute path:
# Fatal: cannot read file /mysysroot/path/to/working/directory/myvers.vers, because of error No such file or directory
clang --target=riscv32-linux-gnu --sysroot=/mysysroot -shared -fuse-ld=eld -nostartfiles -nostdlib empty.c -Wl,--version-script=$PWD/myvers.vers

# lld and bfd both look in the absolute path, not considering the sysroot.
# For this example, lld produces this error (which, make sense--it found the right file, which is empty):
# ld.lld: error: /path/to/working/directory/myvers.vers:1: unexpected EOF
clang --target=riscv32-linux-gnu --sysroot=/mysysroot -shared -fuse-ld=eld -nostartfiles -nostdlib empty.c -Wl,--version-script=$PWD/myvers.vers

# eld looks at the right file when given a relative path (though interestingly it doesn't error on the empty file):
clang --target=riscv32-linux-gnu --sysroot=/mysysroot -shared -fuse-ld=eld -nostartfiles -nostdlib empty.c -Wl,--version-script=myvers.vers
```

### LINKED ISSUE #808: Sysroot is incorrectly prepended to inputs specified in INPUT / GROUP command
Currently, we incorrectly prepend sysroot to inputs specified in INPUT / GROUP linker script commands. 

Reproducible example:

```bash
#!/usr/bin/env bash

mkdir -p A/lib64
mkdir -p A/script

cat >1.c <<\EOF
int foo() { return 1; }
EOF

cat >script.t <<\EOF
GROUP(/lib64/lib1.so)
EOF

cat >main.c <<\EOF
int main() { return 0; }
EOF

clang -o lib1.so -target x86_64-unknown-elf 1.c -shared -fPIC
clang -o main.o -target x86_64-unknown-elf main.c -c 

mv lib1.so A/lib64/lib1.so

ld.eld --sysroot=A -T script.t main.o 
ld.lld --sysroot=A -T script.t main.o
ld.bfd --sysroot=A -T script.t main.o 
```

lld and bfd errors out whereas eld incorrectly finds the lib1.so file.

Another example:

```bash
#!/usr/bin/env bash

mkdir -p A/lib64
mkdir -p A/script

cat >1.c <<\EOF
int foo() { return 1; }
EOF

cat >script.t <<EOF
GROUP($(pwd)/A/lib64/lib1.so)
EOF

cat >main.c <<\EOF
int main() { return 0; }
EOF

clang -o lib1.so -target x86_64-unknown-elf 1.c -shared -fPIC
clang -o main.o -target x86_64-unknown-elf main.c -c 

mv lib1.so A/lib64/lib1.so

ld.eld --sysroot=A -T script.t main.o 
ld.lld --sysroot=A -T script.t main.o
ld.bfd --sysroot=A -T script.t main.o 
```

lld and bfd are correctly able to find lib1.so but eld canont find the lib1.so file.

### PR DESCRIPTION
**Pull request by parth-07**
This commit fixes the logic that determines when the script input path should be prepended with sysroot. The summary of the new behavior:

- sysroot is only prepended to the script inputs when all the below constraints are true:
  - the input is specified in INPUT/GROUP linker script command.
  - The input path begins with '/'.
  - The linker script that contains this INPUT/GROUP command is within the sysroot directory.
- In all other cases, sysroot is not prepended to the script inputs.

Resolves #786
Resolves #808

### CODE REVIEW

File: lib/Input/Input.cpp [hunk 1]
```diff
@@ -151,6 +150,29 @@ bool Input::resolvePath(const LinkerConfig &PConfig) {
...
+
+  // Only apply sysroot for INPUT/GROUP entries when we know which script they
+  // came from and that script is inside sysroot.
+  if (!ParentScriptFile)
+    return false;
+
+  Input *scriptInput = ParentScriptFile->getInput();
+
+  std::string scriptPath = scriptInput->getResolvedPath().getFullPath();
+  std::string sysrootPath = searchDirs.sysroot().getFullPath();
```
Comment (quic-seaswara) [inline lib/Input/Input.cpp:171]: Will this work with reproduce option ?

File: lib/Input/Input.cpp [hunk 2]
```diff
@@ -151,6 +150,29 @@ bool Input::resolvePath(const LinkerConfig &PConfig) {
   return true;
 }
 
+bool Input::shouldPrependSysrootToInput(const LinkerConfig &Config) {
```
Comment (quic-seaswara) [inline lib/Input/Input.cpp]: const function

Please change the name of the function to say its for script inputs.

File: lib/Input/Input.cpp [hunk 3]
```diff
@@ -151,6 +150,29 @@ bool Input::resolvePath(const LinkerConfig &PConfig) {
...
+  auto &searchDirs = Config.directories();
+  if (!searchDirs.hasSysRoot())
+    return false;
+  if (Type != Input::Script)
+    return false;
+  if (FileName.empty() || FileName[0] != '/')
```
Comment (quic-seaswara) [inline lib/Input/Input.cpp:160]: I am not sure how this will be effective on windows. Needs to be tested on windows too.

File: lib/Script/InputCmd.cpp [hunk 4]
```diff
@@ -64,9 +67,11 @@ eld::Expected<void> InputCmd::activate(Module &CurModule) {
...
     switch (Token->type()) {
-    case InputToken::File:
-      ThisBuilder.createDeferredInput(Token->name(), Input::Script);
+    case InputToken::File: {
+      Input *I = ThisBuilder.createDeferredInput(Token->name(), Input::Script);
+      I->setParentScriptFile(parentScriptFile);
       break;
+    }
     case InputToken::NameSpec: {
       ThisBuilder.createDeferredInput(Token->name(), Input::Namespec);
```
Comment (quic-seaswara) [inline lib/Script/InputCmd.cpp:76]: Can we add the parent script file in all cases, and check if the command is INPUT or GROUP ?

File: lib/Input/Input.cpp (hunk 1 above)
Comment (parth-07) [reply lib/Input/Input.cpp:171]: Yes, I think so. We already had this code. Previously, we used to unconditionally prepend the sysroot for script inputs that began with `/`. Now, we only  prepend sysroot for script inputs that begins with `/` if the parent script is within the sysroot directory.

File: lib/Input/Input.cpp (hunk 2 above)
Comment (parth-07) [reply lib/Input/Input.cpp]: Done.

File: lib/Script/InputCmd.cpp (hunk 4 above)
Comment (parth-07) [reply lib/Script/InputCmd.cpp:76]: Can you please explain this in more detail? Currently, we only add parent script for INPUT and GROUP inputs. If I understand correctly, then for the other cases, we do not have any associated parent script.

File: lib/Input/Input.cpp (hunk 3 above)
Comment (parth-07) [reply lib/Input/Input.cpp:160]: Okay!

File: lib/Input/Input.cpp (hunk 1 above)
Comment (quic-seaswara) [reply lib/Input/Input.cpp:171]: Can you please check ?

File: lib/Script/InputCmd.cpp (hunk 4 above)
Comment (quic-seaswara) [reply lib/Script/InputCmd.cpp:76]: I see. Do we need to add this for InputToken::NameSpec too ?

Comment (parth-07) [reply lib/Script/InputCmd.cpp:76]: No, we do not need this for NameSpec. But we do need to fix our behavior for NameSpec with sysroot. GNU LD finds the NameSpec library in all the standard paths inside sysroot. (Paths such as /usr/lib, /lib, /lib64, and so on).

Comment (quic-seaswara) [reply lib/Script/InputCmd.cpp:76]: Please open a follow up ticket on this, We do have this code in `eld::ELDEmulateELF` but that code is not getting triggered.

File: lib/Input/Input.cpp (hunk 1 above)
Comment (parth-07) [reply lib/Input/Input.cpp:171]: I just checked. The linker crashes :'). However, this is not a regression with this patch. We crash without this patch as well.

Reproducer (nightly linker crashes with this):

```bash
#!/usr/bin/env bash

mkdir -p A/lib64
mkdir -p A/script

cat >1.c <<\EOF
int foo() { return 1; }
EOF

cat >script.t <<\EOF
GROUP(/lib64/lib1.so)
EOF

cat >main.c <<\EOF
int main() { return 0; }
EOF

clang -o lib1.so -target x86_64-unknown-elf 1.c -shared -fPIC
clang -o main.o -target x86_64-unknown-elf main.c -c 
mv lib1.so A/lib64/lib1.so
mv script.t A/script.t

ld.eld --sysroot=A -T A/script.t main.o --reproduce a.tar
rm -rf unpacked && mkdir unpacked
tar -xvf a.tar -C unpacked --strip-components=1
cd unpacked
bash -x response.txt
```

I believe this should be treated as a separate issue.

File: lib/Input/Input.cpp [hunk 5]
```diff
@@ -151,6 +150,30 @@ bool Input::resolvePath(const LinkerConfig &PConfig) {
...
+  // came from and that script is inside sysroot.
+  if (!ParentScriptFile)
+    return false;
+
+  Input *scriptInput = ParentScriptFile->getInput();
+
+  std::string scriptPath = scriptInput->getResolvedPath().getFullPath();
+  std::string sysrootPath = searchDirs.sysroot().getFullPath();
+
+  return scriptPath.size() >= sysrootPath.size() &&
```
Comment (quic-areg) [inline lib/Input/Input.cpp:173]: what about a hypothetical `/sdk/sysroot` and a sibling path `/sdk/sysroot_extra`? we should probably use `llvm::sys::fs::equivalent` or similar instead of a raw prefix check

Comment (parth-07) [reply lib/Input/Input.cpp:173]: Here we just need to determine whether the script is within or outside the sysroot. If a script is contained within /sdk/sysroot_extra and the sysroot is /sdk/sysroot, then as per the linker the script is correctly outside the sysroot. The behavior seems correct to me. Can you please let me know if I have missed something?

File: lib/Input/Input.cpp (hunk 1 above)
Comment (parth-07) [reply lib/Input/Input.cpp:171]: I have created an issue to track this #818

File: lib/Script/InputCmd.cpp (hunk 4 above)
Comment (parth-07) [reply lib/Script/InputCmd.cpp:76]: I have created an issue to track this: #819

File: lib/Input/Input.cpp (hunk 3 above)
Comment (quic-seaswara) [reply lib/Input/Input.cpp:160]: Do we need to follow up with windows testing ?
