### PR TITLE
Do not check PHDR errors for partial link

### LINKED ISSUE #118: eld errors out when doing partial link if the linker script contains `PHDRS`
eld errors out when doing partial link if the linker script contains `PHDRS`. 

Reproducible example:

```bash
#!/usr/bin/env bash

cat >1.c <<\EOF
int foo() { return 1; }

int var = 3;
EOF

cat >script.t <<\EOF
PHDRS {
  A PT_LOAD;
  B PT_LOAD;
}

SECTIONS {
  .text : { *(.text.*) } :B
  .data : { *(.data.*) }
}
EOF

clang -o 1.o 1.c -target riscv64 -c -ffunction-sections -fdata-sections
ld.eld -m elf64lriscv -o 1.out 1.o -T script.t -r
```

Output:
```
Error: Loadable section .text not in any load segment
Error: Loadable section .data not in any load segment
Fatal: Linking had errors.
```

Instead of erroring out, the linker should simply ignore `PHDRS` when doing partial link.

### PR DESCRIPTION
**Pull request by parth-07**
This commit fixes the incorrect PHDR-related linker error when doing partial link. The linker should ignore the PHDRS specified in the linker script when doing partial link.

Closes #118

### CODE REVIEW

File: lib/Target/GNULDBackend.cpp [hunk 1]
```diff
@@ -3152,7 +3152,7 @@ bool GNULDBackend::layout() {
     doPostLayout();
   }
 
-  if (m_Module.getScript().phdrsSpecified())
+  if (m_Module.getScript().phdrsSpecified() && !config().isLinkPartial())
```
Comment (quic-seaswara) [inline lib/Target/GNULDBackend.cpp:3145]: We should also raise a warning that PHDR's are used for partial linking with -Wlinker-script. 

Why Is it even valid to use a linker script with PHDR's and partial linking ?

Comment (parth-07) [reply lib/Target/GNULDBackend.cpp:3145]: > We should also raise a warning that PHDR's are used for partial linking with -Wlinker-script.

Yes, I plan to do this in a separate patch.

> Why Is it even valid to use a linker script with PHDR's and partial linking ?

I am not sure about this. I think it is for convenience purposes. We can choose to error out here but both GNU ld and lld do not report any error for this. Should I raise an issue in LLVM for erroring out when `PHDRS` is specified with partial link?

Comment (quic-seaswara) [reply lib/Target/GNULDBackend.cpp:3145]: Sure.

Comment (quic-seaswara) [reply lib/Target/GNULDBackend.cpp:3145]: MEMORY/PHDRS/Section address/AT all would be warnings as well.

Dot assignments outside the section would be a warning IMO as well.

Comment (parth-07) [reply lib/Target/GNULDBackend.cpp:3145]: I created an LLD issue for PHDR warning this morning: https://github.com/llvm/llvm-project/issues/142926. I will create issues for MEMORY/section address/AT/... as well depending upon their response for the PHDR warning issue.

**Review by quic-seaswara — APPROVED** [review]
