### PR TITLE
Reiterate layout step until section addresses converge

### LINKED ISSUE #687: Incorrect layout when there is a forward reference in a dot assignment
We have incorrect layout when there is a forward reference in a dot assignment.

Reproducer:

```bash
#!/usr/bin/env bash

cat >1.c <<\EOF
int foo() { return 1; }

int val = 3;
EOF


cat > script.t << '!'
SECTIONS {
  . = u;
  .text : { *(.text*) }
  .data : { *(.data*) }
  .comment : { *(.comment*) }
  u = 0x3000;
}
!


LDs=(ld.eld ld.lld aarch64-none-elf-ld.bfd)
SFs=(eld lld bfd)

clang -o 1.o --target=aarch64-unknown-elf 1.c -c -ffunction-sections

for i in "${!SFs[@]}"; do
  ${LDs[$i]} -o 1.${SFs[$i]}.out 1.o -T script.t -Map 1.${SFs[$i]}.map.txt
done
```

Running `llvm-readelf -S 1.eld.out` outputs:
```
There are 7 section headers, starting at offset 0x1280:

Section Headers:
  [Nr] Name              Type            Address          Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            0000000000000000 000000 000000 00      0   0  0
  [ 1] .text             PROGBITS        0000000000000000 001000 000008 00  AX  0   0  4
  [ 2] .data             PROGBITS        0000000000000008 001008 000004 00  WA  0   0  4
  [ 3] .comment          PROGBITS        0000000000000000 00100c 0000ce 01  MS  0   0  1
  [ 4] .shstrtab         STRTAB          0000000000000000 0010da 000030 00      0   0  1
  [ 5] .symtab           SYMTAB          0000000000000000 001110 000108 18      6   8  8
  [ 6] .strtab           STRTAB          0000000000000000 001218 00002d 00      0   0  1
```

The address of `.text` section should be `0x3000` instead of `0x1000`.

### PR DESCRIPTION
**Pull request by parth-07**
This commit modifies the layout step to reiterate until the section addresses converge. The reiteration has an upper limit of 4. On reaching this limit, a warning is emitted and the layout reiteration is stopped.

Please note that this reiteration limit is for layout iterations before relaxations take place. After a layout relaxation pass, the reiteration count is reset to 0.

Resolves #687

### CODE REVIEW

File: lib/Target/CreateScriptProgramHeaders.hpp [hunk 1]
```diff
@@ -87,319 +87,333 @@ bool GNULDBackend::createScriptProgramHdrs() {
...
-  reset_state();
+    changedOutputSection = nullptr;
+    if (linkerScriptHasMemoryCommand)
+      clearMemoryRegions();
+  };
 
-  while (out != outEnd) {
-    bool useSetLMA = false;
+  int preRelaxPassIter = 0;
+  do {
```
Comment (quic-areg) [inline lib/Target/CreateScriptProgramHeaders.hpp]: This is a massive loop that requires indenting everything and makes the diff really large. I wonder if this can be avoided somehow? Can we isolate the single-pass into a new function and then have a small loop in relax() or somewhere else?

File: lib/Target/GNULDBackend.cpp [hunk 2]
```diff
@@ -4017,6 +4017,8 @@ bool GNULDBackend::maySkipRelocProcessing(Relocation *pReloc) const {
 bool GNULDBackend::relax() {
   bool finished = false;
   int iteration = 0;
+  // Limit the number of layout passes to avoid non-converging layouts.
+  const int maxPreRelaxationPasses = 4;
```
Comment (quic-areg) [inline lib/Target/GNULDBackend.cpp]: Can we define this in one place?

**Comment by parth-07** [comment]
> Why are you exposing maxPreRelaxationPasses to the function ?

We need to use `maxPreRelaxationPasses` in createProgramHdrs` and `createScriptProgramHdrs` function to determine
the number of times the layout needs to be computed when it is not getting converged.

> I feel createProgramHeaders is becoming overly iterative.
> The logic can be contained in GNULDBackend.

To push the logic in GNULDBackend, we will need to refactor `createProgramHdrs` and `createScriptProgramHdrs` so that
we can run the inner loop of these functions directly from GNULDBackend. However, in our offline discussions, you told not
to refactor those functions as of now as that will increase the testing requirement.

File: include/eld/Target/GNULDBackend.h [hunk 3]
```diff
@@ -1184,6 +1189,8 @@ class GNULDBackend {
   GNUVerDefFragment *GNUVerDefFrag = nullptr;
   std::unordered_map<const ResolveInfo *, uint16_t> OutputVersionIDs;
 #endif
+  OutputSectionEntry * changedOutputSection = nullptr;
```
Comment (quic-areg) [inline include/eld/Target/GNULDBackend.h]: Layout iterations only continue when section addresses change, but what about symbol-only forward references?

```ld
cat > 1.c << \!
int foo() {return 0;}
!

cat > cycle.t << \!
SECTIONS {
  . = 0x1000;
  .text : {*(.text*)}
  a = b + 4;
  b = a + 4;
}
!

cat > sym.t << \!
PHDRS {TEXT PT_LOAD;}
SECTIONS {
  . = 0x1000;
  .text : {*(.text*)} : TEXT
  a = b + 4;
  b = c + 4;
  c = 0x2000;
}
!

clang -c 1.c

ld.eld 1.o -T sym.t # a,b,c = 0x8,    0x2004, 0x2000
ld.lld 1.o -T sym.t # a,b,c = 0x2008, 0x2004, 0x2000

ld.lld 1.o -T cycle.t # error: assignment to symbol a does not converge
ld.eld 1.o -T cycle.t # a = 0x14; b=0x18
```

File: lib/Target/CreateScriptProgramHeaders.hpp (hunk 1 above)
Comment (parth-07) [reply lib/Target/CreateScriptProgramHeaders.hpp]: >  Can we isolate the single-pass into a new function and then have a small loop in relax() or somewhere else?

That will also result in a huge diff, same as it is right now.

> I wonder if this can be avoided somehow?

We can keep the indentation of the original loop as before, but still enclose it within do .. while(), however, then the indentation would be incorrect and reading the code in future might be misleading in the future due to incorrect indentation.

File: include/eld/Target/GNULDBackend.h (hunk 3 above)
Comment (parth-07) [reply include/eld/Target/GNULDBackend.h]: > Layout iterations only continue when section addresses change, but what about symbol-only forward references?

I plan to handle symbol address convergence in the next patch. The subsequent patches will add support for symbol address convergence, improved diagnostics related to layout iterations and convergence, and some heuristics to reduce the number of iterations wherever possible.

File: lib/Target/CreateScriptProgramHeaders.hpp [hunk 4]
```diff
@@ -58,7 +58,7 @@ bool GNULDBackend::createScriptProgramHdrs() {
       _segmentsForSection[m_phdr->getOutputSection()].push_back(
           _segments[EhdrInLoadSegment->getSpec()->name()]);
   };
-
+  bool linkerScriptHasMemoryCommand = m_Module.getScript().hasMemoryCommand();
   auto reset_state = [&](OutputSectionEntry *OS = nullptr) {
```
Comment (quic-areg) [inline lib/Target/CreateScriptProgramHeaders.hpp:62]: we reuse the segment table across passes; segments from a transient layout can stick around:

In the first pass we create a new `PT_LOAD` for `.bar` due to the forward reference that remains even after `v` is fixed:

```bash
cat > 1.c << \!
[[gnu::section(".foo")]] int foo = 1;
[[gnu::section(".bar")]] int bar = 2;
!

cat > fwd.t << \!
SECTIONS {
  . = u;
  .foo : {*(.foo)}
  . = v;
  .bar : {*(.bar)}
  u = 0x1000;
  v = u + 0x10;
}
!

cat > nofwd.t << \!
SECTIONS {
  . = 0x1000;
  .foo : {*(.foo)}
  . = 0x1010;
  .bar : {*(.bar)}
}
!

clang -c 1.c
ld.eld 1.o -T fwd.t -o fwd     # two PT_LOADs with .foo and .bar separate.
ld.eld 1.o -T nofwd.t -o nofwd # single PT_LOAD with .foo and .bar together.

ld.lld 1.o -T fwd.t -o fwd
ld.lld 1.o -T fwd.t -o nofwd

llvm-readelf -l fwd nofwd
```

File: lib/Target/GNULDBackend.cpp (hunk 2 above)
Comment (parth-07) [reply lib/Target/GNULDBackend.cpp]: Thank you for catching this. This variable is not used at all. I added a member variable of the same name and that is being used everywhere. I have removed it now.

File: include/eld/Target/GNULDBackend.h [hunk 5]
```diff
@@ -1184,6 +1189,8 @@ class GNULDBackend {
...
+  const int maxPreRelaxationPasses = 4;
 };
```
Comment (quic-areg) [inline include/eld/Target/GNULDBackend.h:1211]: It looks like lld's max passes is 5. Is there any reason we picked a different number?

File: include/eld/Diagnostics/DiagLayouts.inc [hunk 6]
```diff
@@ -62,4 +62,6 @@ DIAG(warning_zero_sized_fragment_for_non_zero_symbol, DiagnosticEngine::Warning,
 DIAG(error_offset_not_assigned_for_output_section, DiagnosticEngine::Error,
      "Requested offset for output section %0 has not yet been assigned")
 DIAG(warn_empty_segment, DiagnosticEngine::Warning,
-     "Empty segment: '%0'")
\ No newline at end of file
+     "Empty segment: '%0'")
+DIAG(note_section_address_not_converging, DiagnosticEngine::Note,
```
Comment (quic-areg) [inline include/eld/Diagnostics/DiagLayouts.inc:65]: should this be a warning instead?

File: lib/Target/CreateScriptProgramHeaders.hpp [hunk 7]
```diff
@@ -87,319 +87,333 @@ bool GNULDBackend::createScriptProgramHdrs() {
...
+        config().raise(Diag::cannot_set_at_address) << cur->name();
+        hasError = true;
+      }
 
-    if (cur->isFixedAddr() && (vma != cur->addr())) {
-      config().raise(Diag::cannot_set_at_address) << cur->name();
-      hasError = true;
-    }
+      setVMA(*cur, vma, /*ignoreChangedSection=*/false);
+      cur->setAddr(vma);
```
Comment (quic-areg) [inline lib/Target/CreateScriptProgramHeaders.hpp]: do we need both `setVMA` and `cur->setAddr()`?

File: lib/Target/CreateScriptProgramHeaders.hpp (hunk 1 above)
Comment (quic-areg) [reply lib/Target/CreateScriptProgramHeaders.hpp]: I was thinking to first refactor the single-pass in a separate patch, and then this PR just becomes adding a loop

If refactoring is not an option, can the loop be a `while()` loop instead of a `do...while`? Since the function is massive it's not obvious what condition we are looping over until we find the end of the loop many lines down.

Regardless of whatever decision is taken here I think the two `.hpp` files could benefit from refactoring somewhere down the line.

File: lib/Target/CreateScriptProgramHeaders.hpp (hunk 4 above)
Comment (parth-07) [reply lib/Target/CreateScriptProgramHeaders.hpp:62]: > we reuse the segment table across passes; segments from a transient layout can stick around:

Thank you for mentioning this. This can indeed create some issues.

> ld.eld 1.o -T fwd.t -o fwd     # two PT_LOADs with .foo and .bar separate.
> ld.eld 1.o -T nofwd.t -o nofwd # single PT_LOAD with .foo and .bar together.

The behavior here is the same as before this patch. 

I will change the patch functionality so that the segments from a transient layout do not cause issues.

File: include/eld/Diagnostics/DiagLayouts.inc (hunk 6 above)
Comment (parth-07) [reply include/eld/Diagnostics/DiagLayouts.inc:65]: This is a note because with warning the link will fail if `--fatal-warning` is used.

File: lib/Target/CreateScriptProgramHeaders.hpp (hunk 7 above)
Comment (parth-07) [reply lib/Target/CreateScriptProgramHeaders.hpp]: No, thank you for catching this. I am fixing this.

File: include/eld/Target/GNULDBackend.h (hunk 5 above)
Comment (parth-07) [reply include/eld/Target/GNULDBackend.h:1211]: LLD's has two different kind of max passes, one is `30` and the other is `5`. LLD uses the combination of these two during the layout. eld layout mechanism is different from LLD. `4` is not fixed here, and can be changed if a greater / smaller value seems better in the future. I believe that `4` is appropriate here as a good upper-bound, especially after adding some of the heuristics to converge faster that are planned as a follow-up after this patch. And if the layout converges in the 2nd iteration, then the remaining iterations will be skipped.

File: lib/Target/CreateScriptProgramHeaders.hpp (hunk 4 above)
Comment (parth-07) [reply lib/Target/CreateScriptProgramHeaders.hpp:62]: >  ld.eld 1.o -T fwd.t -o fwd # two PT_LOADs with .foo and .bar separate.
>  ld.eld 1.o -T nofwd.t -o nofwd # single PT_LOAD with .foo and .bar together.

With the latest patchset, we have single PT_LOAD segment in both the cases. Thank you for pointing this out.

File: lib/Target/CreateScriptProgramHeaders.hpp (hunk 1 above)
Comment (parth-07) [reply lib/Target/CreateScriptProgramHeaders.hpp]: I have changed the design so that now we don't have large number of changes in this PR.

> Regardless of whatever decision is taken here I think the two .hpp files could benefit from refactoring somewhere down the line.

Totally agree on this.

File: include/eld/Target/GNULDBackend.h [hunk 8]
```diff
@@ -757,6 +758,24 @@ class GNULDBackend {
   // -------------------- Finalize Layout callback ----------------
   virtual bool finalizeLayout() { return true; }
 
+  // -------------------- Layout convergence snapshot -------------------
```
Comment (quic-areg) [inline include/eld/Target/GNULDBackend.h]: As a tangent, I am generally not a fan of this kind of comment.

`  // -------------------- Layout convergence snapshot -------------------`
`  // -------------------- Finalize Layout callback ----------------`

The length of the `----` portions are always inconsistent. The comment would look a lot better as 

`// Layout convergence`

Or in some cases, omitted entirely.

File: include/eld/Target/GNULDBackend.h [hunk 9]
```diff
@@ -757,6 +758,24 @@ class GNULDBackend {
...
+
+  // Capture current layout snapshot keyed by OutputSectionEntry*.
+  LayoutSnapshot captureLayoutSnapshot() const;
+
+  // Compare two snapshots for exact address convergence.
+  // Returns nullptr if converged; otherwise returns a changed OutputSectionEntry.
+  const OutputSectionEntry *isConverged(const LayoutSnapshot &Prev,
+                                        const LayoutSnapshot &cur) const;
+
   // --- Exclude symbol support
```
Comment (quic-areg) [inline include/eld/Target/GNULDBackend.h:782]: Tangent: This is an example where the comment is better omitted. It just repeats the function name, which is already self-describing.

File: include/eld/Target/GNULDBackend.h [hunk 10]
```diff
@@ -757,6 +758,24 @@ class GNULDBackend {
   // -------------------- Finalize Layout callback ----------------
   virtual bool finalizeLayout() { return true; }
 
+  // -------------------- Layout convergence snapshot -------------------
+  struct SectionAddrs {
+    uint64_t vma = 0;
+    uint64_t lma = 0;
+  };
+
+  struct LayoutSnapshot {
```
Comment (quic-areg) [inline include/eld/Target/GNULDBackend.h:772]: can this be 
```cpp
using LayoutSnapShot = llvm::DenseMap...
```
?

File: include/eld/Diagnostics/DiagLayouts.inc (hunk 6 above)
Comment (quic-areg) [reply include/eld/Diagnostics/DiagLayouts.inc:65]: non-convergence implies potentially incorrect output, and that should be a warning imo. A note may be be ignored allowing potentially bad code to ship.

File: include/eld/Target/GNULDBackend.h [hunk 11]
```diff
@@ -757,6 +758,24 @@ class GNULDBackend {
...
+    llvm::DenseMap<const OutputSectionEntry *, SectionAddrs> outSections;
```
Comment (quic-seaswara) [inline include/eld/Target/GNULDBackend.h:773]: can we make this a vector of all the output sections ? 

Since we know the order in this case, it  is much easier to compare and return ? 

```
struct { 
   OutputSectionEntry *OS;
   uint64_t vma;
   uint64_t lma;
   operator ==(OSE &right) {
   ... 
   }
} OSE;
std::vector<OSE> OutputSections;
```

**Review by quic-seaswara — COMMENTED** [review]
I generally like the direction we are going with this.

File: include/eld/Target/GNULDBackend.h (hunk 8 above)
Comment (parth-07) [reply include/eld/Target/GNULDBackend.h]: I agree with your suggestion. I have omitted the comment here entirely.

File: include/eld/Target/GNULDBackend.h (hunk 9 above)
Comment (parth-07) [reply include/eld/Target/GNULDBackend.h:782]: Agreed! I have removed the redundant function comment.

File: include/eld/Target/GNULDBackend.h (hunk 10 above)
Comment (parth-07) [reply include/eld/Target/GNULDBackend.h:772]: This is a `struct` intentionally. The next patch will add another member to the struct for tracking symbol values.

File: include/eld/Target/GNULDBackend.h (hunk 11 above)
Comment (parth-07) [reply include/eld/Target/GNULDBackend.h:773]: I tried doing this. It seems that the order of output sections can change in the `createProgramHdrs` call due to this code:

```cpp
// If there is an AT Table. Lets try to check the dot value with the
// section specified in the AT Table.
if (atTable.size() && m_AtTableIndex < atTable.size()) {
  ELFSection *atSection = atTable[m_AtTableIndex];
  if (curIsDebugSection ||
       ((atSection->addr() < dotSymbol->value()) ||
       (scriptvma && (*scriptvma > atSection->addr())))) {
    out = script.sectionMap().insert(out, atSection);
```

The `out = script.sectionMap().insert(out, atSection);` call can change the output section order.

Comment (quic-seaswara) [reply include/eld/Target/GNULDBackend.h:773]: ah! at sections are very rare and the feature is going away FYI. I would like to see that we have the order of output sections as a vector.

Comment (partaror) [reply include/eld/Target/GNULDBackend.h:773]: > the feature is going away 

But the feature is not away yet. Can we remove the at feature currently? I do not want the layout convergence functionality to break at some cases as it can get difficult to track.
